apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: agrocd-server-ingress
spec:
  ingressClassName: nginx
  rules:
  - host: agrocd.baonk.site
    http:
      paths:
      - backend:
          service:
            name: argocd-server
            port:
              number: 443
        path: /
        pathType: Prefix