apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-world
spec:
  selector:
    matchLabels:
      app: hello-world
  template:
    metadata:
      labels:
        app: hello-world
    spec:
      nodeName: master-1
      containers:
      - name: hello-world
        # image: harbor.baonk.io/dev-registry/hello-world-node:v1
        image: private-docker-registry.baonk.com:5000/dev-registry/hello-node:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: hello-world-port
spec:
  type: NodePort
  selector:
    app: hello-world
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30004
