apiVersion: apps/v1
kind: Deployment
metadata:
  name: chat-app-backend
spec:
  selector:
    matchLabels:
      app: chat-app-backend
  template:
    metadata:
      labels:
        app: chat-app-backend
    spec:
      containers:
      - name: chat-app-backend
        image: khacbaocsek19/chat-app:v1
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "100m"
        env:
        - name: MONGODB_SERVER
          value: 'mongodb://root:admin12345@chat-app-db:27017/chat-app?authSource=admin'
        - name: COOKIE_SECRECT
          value: '123456'
        - name: JWT_SECRECT
          value: '123456'
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: chat-app-port
spec:
  type: NodePort
  selector:
    app: chat-app-backend
  ports:
  - port: 3000
    targetPort: 3000
    nodePort: 30005
