apiVersion: v1
kind: Secret
metadata:
  name: mongo-secret
type: kubernetes.io/basic-auth
stringData:
  password: admin12345
# ---
# apiVersion: v1
# kind: Secret
# metadata:
#   name: mongo-url-secret
# type: kubernetes.io/basic-auth
# stringData:
#   password: mongodb://root:admin12345@chat-app-db:27017/BK-Chat?authSource=admin
---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: mongo-pv-volume
  labels:
    type: local
spec:
  storageClassName: mongo-pv
  capacity:
    storage: 2Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: "/data/mongo"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-pv-claim
spec:
  storageClassName: mongo-pv
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 2Gi
