local.file_match "tmplogs" {
    path_targets = [{"__path__" = "/tmp/*.log"}]
}

loki.source.file "local_files" {
    targets    = local.file_match.tmplogs.targets
    forward_to = [loki.relabel.add_static_label.receiver]
}

loki.relabel "add_static_label" {
    forward_to = [loki.write.local_loki.receiver]

    rule {
        source_labels = ["flog"]
        target_label = "service"
        regex         = "/(.*)"
    }
}

loki.write "local_loki" {
    endpoint {
        url = "http://gateway:3100/loki/api/v1/push"
        tenant_id = "tenant1"
    }
}