version: "3.4"
services:
  cadvisor:
    image: gcr.io/google-containers/cadvisor:latest
    container_name: cadvisor
  # ports:
  #   - 8080:8080
    volumes:
    - /:/rootfs:ro
    - /var/run:/var/run:rw
    - /sys:/sys:ro
    - /var/lib/docker/:/var/lib/docker:ro
  
  # node-exporter:
  #   image: prom/node-exporter:v1.4.0
  #   container_name: node-exporter
  #   restart: unless-stopped
  # ports:
    # - 9100:9100
    # volumes:
    #   - /proc:/host/proc:ro
    #   - /sys:/host/sys:ro
    #   - /:/rootfs:ro
    # command:
    #   - '--path.procfs=/host/proc'
    #   - '--path.rootfs=/rootfs'
    #   - '--path.sysfs=/host/sys'
    #   - '--collector.filesystem.mount-points-exclude=^/(sys|proc|dev|host|etc)($$|/)'
  mongodb-exporter:
    image: percona/mongodb_exporter:0.35
    container_name: mongodb_exporter
    ports: 
      - 8005:9216
      - 17001:17001
    command: 
      - --mongodb.uri=mongodb://admin:admin12345@mongodb:27017

  prometheus:
    image: prom/prometheus:v2.39.1
    container_name: prometheus
    ports:
    - 8004:9090
    command:
    - --config.file=/etc/prometheus/prometheus.yml
    volumes:
    - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
    - cadvisor
    # - node-exporter
    - mongodb-exporter
  grafana:
    image: grafana/grafana:9.2.3
    container_name: grafana
    ports:
    - 8003:3000
    user: "$UID:$GID"
    volumes:
    - /data/grafana:/var/lib/grafana
    restart: always
    depends_on:
    - prometheus
networks:
  default:
    name: mongodb_default
    external: true